package nz.ac.massey.buto.io;

/**
 * Event object generated by DataSource objects. Informs listeners of the beginning and ending of loading profile and oracles.
 * 
 * @author Fergus Hewson
 *
 */
public class DataSourceEvent {

	//************************************************************************
	// Event Types
	public static final String OPERATION_STARTED = 		"OPERATION_STARTED";
	public static final String OPERATION_PROGRESS = 	"OPERATION_PROGRESS";
	public static final String OPERATION_ERROR = 		"OPERATION_ERROR";
	public static final String OPERATION_COMPLETE = 	"OPERATION_COMPLETE";
	
	//************************************************************************
	// Operation Types
	public static final String GET_PROFILE_NAMES = 	"GET_PROFILE_NAMES";
	public static final String GET_ORACLE_NAMES = 	"GET_ORACLE_NAMES";
	
	public static final String GET_PROFILE = 		"GET_PROFILE";
	public static final String GET_ORACLE = 		"GET_ORACLE";
	
	public static final String SAVE_PROFILE = 		"SAVE_PROFILE";
	public static final String SAVE_ORACLE = 		"SAVE_ORACLE";
	
	public static final String DELETE_PROFILE = 	"DELETE_PROFILE";
	public static final String DELETE_ORACLE = 		"DELETE_ORACLE";
	
	/**
	 * The type of the event, OPERATION_STARTED, OPERATION_PROGRESS or OPERATION_COMPLETE.
	 */
	private String eventType;
	
	/**
	 * The operation type of the event. 
	 */
	private String operationType;
	
	/**
	 * Integer representing the progress of the operation being performed.
	 */
	private int progress;
	
	/**
	 * Creates a new event object with the provided operation and event type.
	 * 
	 * @param operationType The type of the operation being performed, loading, saving and deleting oracles and profiles.
	 * @param eventType The event type for this event, can signify the start or completion of an operation or progress made during an operation.
	 */
	public DataSourceEvent(String operationType, String eventType){
		this.operationType = operationType;
		this.eventType = eventType;
	}
	
	/**
	 * Creates a progress event for the given operation type.
	 * @param progress The progress made by the operation.
	 */
	public DataSourceEvent(String operationType, int progress){
		this.operationType = operationType;
		this.eventType = OPERATION_PROGRESS;
		this.progress = progress;
	}

	/**
	 * Gets the event type for this event.
	 * @return The event type.
	 */
	public String getEventType() {
		return eventType;
	}
	
	/**
	 * Gets the operation type for this event.
	 * @return The operation type for this event.
	 */
	public String getOperationType(){
		return operationType;
	}
	
	/**
	 * Gets the progress made by an operation, will return null if this event does not 
	 * have a type of OPERATION_PROGRESS.
	 * @return The progress of the current operation by the data source, null if this event is not an OPERATION_PROGRESS event.
	 */
	public int getProgress() {
		return progress;
	}
}
