package nz.ac.massey.buto.analysis.notifications;

/**
 * A classification error object generated by the notifcation classifier.
 * 
 * @author fahewson
 *
 */
public class NotificationDifference {
	
	
	private String message;
	
	public NotificationDifference(String message){
		this.message = message;
	}

	/**
	 * Gets the error message.
	 * 
	 * @return the message
	 */
	public String getMessage() {
		return message;
	}
	
}
