package nz.ac.massey.buto.jmx.collector;
/**
 * Interface for objects that want to listen to events generated by the JMXCollector.
 * 
 * @author Fergus Hewson
 *
 */
public interface JMXCollectorListener {
	/**
	 * Process a given JMXCollector event.
	 * 
	 * @param event The event to process.
	 */
	public void processJMXCollectorEvent(JMXCollectorEvent event);
}
